### ISSUE TITLE
Is there a way to go to a symbol containing hyphens?

### ISSUE THREAD

**Issue by GitMensch** [gediminasz/ctags-companion#32]
Some programming languages allow hypens in their identifiers. The .tags file has those definitions in, but the "go to" seems to "stop" at the hyphen.

**Comment by gediminasz** [comment]
Could you provide an example repo or a snippet of code I could reproduce this with?

By the way, have you tried playing around with the `editor.wordSeparators` setting?

**Comment by GitMensch** [comment]
Example repo: https://github.com/contextfreecode/cobol-explore

Ideally the following should be able to be opened by CTRL-click (the ctags file has those as content):

* a file name `COPY` as in https://github.com/contextfreecode/cobol-explore/blob/814c7415ba94da0c9e0fa1bf5dbf72350ac25f4f/game.cbl#L6
* a variable reference, like in https://github.com/contextfreecode/cobol-explore/blob/814c7415ba94da0c9e0fa1bf5dbf72350ac25f4f/game-option.cpy#L20 (has an hyphen)
* a procedure reference like in https://github.com/contextfreecode/cobol-explore/blob/814c7415ba94da0c9e0fa1bf5dbf72350ac25f4f/game-stat.cpy#L29 (also with an hyphen)
* a sub-program `CALL` like in https://github.com/contextfreecode/cobol-explore/blob/814c7415ba94da0c9e0fa1bf5dbf72350ac25f4f/hi.cbl#L9-11 (the first one is a "foreign" symbol, the second is a symbol that is defined in the same source)

**Comment by gediminasz** [comment]
@GitMensch is this issue still relevant? 

Had a quick look today. Some findings:

1. Removing hyphens (or anything) from `editor.wordSeparators` does not seem to help. Cobol language definition is required. See down below.
2. I have to add ` --langmap=cobol:+.cpy` to the ctags command to make it index `.cpy` files, e.g.:
   ```
   "ctags-companion.command": "ctags -R --fields=+nKz -f .vscode/.tags --langmap=cobol:+.cpy",
   ```

This extension uses [getWordRangeAtPosition API](https://code.visualstudio.com/api/references/vscode-api#TextDocument.getWordRangeAtPosition) which by default uses language specific word definitions.

The problem is that out of the box vscode does not include Cobol language definition so it thinks that `.cpy` files are Python, `.cbl` files are Plain Text and so on (i.e. languages where hyphens are a word separator). You can see the detected language in the bottom right corner of the editor. 

![Screenshot 2023-07-04 at 12 48 17](https://github.com/gediminasz/ctags-companion/assets/699568/236422ea-8ee4-4cb1-86d0-73e2c01370e3)

I can work around this by installing an extension which provides a Cobol language definition. I've picked this one at random: https://marketplace.visualstudio.com/items?itemName=broadcomMFD.cobol-language-support and it seems to work. @GitMensch have you tried using any of the Cobol extensions?

**Comment by GitMensch** [comment]
> Is this issue still relevant?

Yes.

Looking at your answer, we need both a ctags configuration _and_ support by the word definition.

I'm not sure about this but it seems that one may need to set both https://github.com/Microsoft/vscode-docs/blob/main/api/language-extensions/language-configuration-guide.md#word-pattern `wordPattern` in the language definition and `editor.wordSeparators`.

Are you sure that the _working_ go to feature still uses ctags-companion and not the cobol extension?


In any case: should I move the part "Ideally the following should be able to be opened by CTRL-click (the ctags file has those as content" out to a separate issue?

**Comment by gediminasz** [comment]
> I'm not sure about this but it seems that one may need to set both https://github.com/Microsoft/vscode-docs/blob/main/api/language-extensions/language-configuration-guide.md#word-pattern wordPattern in the language definition and editor.wordSeparators.

I think we can forget about the `editor.wordSeparators` setting. It does not seem to be relevant after all.

As for `wordPattern`, it does not look like a user setting. It is something that should be defined in a language extension. For this reason I was suggesting you to try installing an extension which provides Cobol language support.

> Are you sure that the working go to feature still uses ctags-companion and not the cobol extension?

I am fairly sure, because if I delete the `.tags` file it says "no definition found". Also using debugger I can see that `getWordRangeAtPosition` returns a correct symbol such as `option-time` rather than just `option` or `time`.

> In any case: should I move the part "Ideally the following should be able to be opened by CTRL-click (the ctags file has those as content" out to a separate issue?

No, it's okay. The problem scope has not changed.

So all in all @GitMensch I would suggest you explore some of the Cobol extensions and see if it works for you.

Otherwise the next best thing I can come up with is exposing the `regex` parameter of `getWordRangeAtPosition` as a setting for you to configure.

**Comment by GitMensch** [comment]
> Otherwise the next best thing I can come up with is exposing the regex parameter of getWordRangeAtPosition as a setting for you to configure.

That would be useful in any case.

> The problem scope has not changed.

Hm, the following has no hyphen in it and still does not work:

> Example repo: https://github.com/contextfreecode/cobol-explore
> 
> Ideally the following should be able to be opened by CTRL-click (the ctags file has those as content): [...] a sub-program `CALL` like in https://github.com/contextfreecode/cobol-explore/blob/814c7415ba94da0c9e0fa1bf5dbf72350ac25f4f/hi.cbl#L9-11 (the first one is a "foreign" symbol, the second is a symbol that is defined in the same source)

**Comment by gediminasz** [comment]
I have made a release containing a fix for looking up symbols containing hyphens: https://github.com/gediminasz/ctags-companion/commit/235097d7b987333b5e4cb6c2881c2eeb5c0e43ef

In combination with another extension which provides Cobol language definition, I was able to get "jump to definition" to work.

Cobol language extension used: https://marketplace.visualstudio.com/items?itemName=bitlang.gnucobol

I just had to adjust the `ctags` command setting:

```
"ctags-companion.command": "ctags -R --fields=+nKz --langmap=cobol:+.cpy",
```

@GitMensch let me know if it works.
